apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP #because LoadBalancer will expose this api to outside world.
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80