apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: aadeetyeah/kub-demo-tasks:latest
          env: 
            - name: AUTH_ADDRESS
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks
          volumeMounts:
            - name: tasks
              mountPath: /app/tasks
      volumes:
        - name: tasks
          emptyDir: {}